### ISSUE TITLE
please add a Mac OS target

### ISSUE THREAD

**Issue by jaywardell** [Weebly/Try#2]
Very useful class.  One request:  I tried to add Weebly/Try to my OS X project via carthage, but your project has no OS X target, so no framework was created.  So I'm left copying your source into my project.  Not a big deal, it looks like it hasn't needed to be updated in a while, but still it would be nice to have it integrated into carthage.

Thanks.

**Comment by rudedogg** [comment]
Same issue:

```bash
*** Skipped building Try due to the error:
Dependency "Try" has no shared framework schemes for any of the platforms: Mac
```
